# Generated by Django 4.0.3 on 2022-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='iamges/'),
        ),
    ]
